### PR TITLE
Refactor into modules + Prettier formatting

### PR DESCRIPTION
**Pull request by jshph**
Hi @rpggio !

First off, thanks for your great work with this plugin. I've been working on an LLM plugin that accomplishes something different and I recently had the thought that Canvas would make it a whole lot more intuitive. That's when I came across Chat Stream.

I've since prototyped on top of your master branch and things seem to be working super well (very excited to see this!), so before continuing further I decided a major refactor (without changing your existing functionality) would greatly make my plugin sit well on top of yours.

That sets some context for this refactor. In summary, I have
1. Moved things out of `ChatStreamPlugin.ts`, either into `ai-nodes.ts` or into `canvas-patches.ts`. IMHO, the core plugin ts file should be slim, so I am just separating concerns.
2. Used Prettier to establish consistent formatting (here I tried to keep as consistent with your existing formatting as possible, i.e. 2-space indent, single quotes) -- just helps development with my local IDE. Prettier does, however, introduce some other reformatting in the process -- apologies for the clutter. I also offer my settings.json file here, which allows for reformat-on-save with Prettier.

That's it! I am open to your thoughts, and just an FYI that I will be continuing to iterate on top of this work in coming days. If you don't have capacity to review this near-term, that would be great to know. Many thanks! Dropped you a tip ;)

### CODE REVIEW

**Comment by rpggio** [comment]
Thanks @jshph !
Excited to see what you have planned. I had some ideas about where to take the project next, but am pausing due to starting a new job.

**Comment by rpggio** [comment]
I installed Prettier, but vscode wants to reorganize imports. If there is something else to do to avoid churning the imports, LMK.

**Comment by jshph** [comment]
Many thanks for merging! And best of luck with the new gig.

You can try adding `"sortImports": false` to the .prettierrc and hopefully that doesn't reorder your imports?

**Comment by jshph** [comment]
If you want to share your ideas sometime, maybe in a separate issue or over email, I'm very curious. I had started with an MVP but I feel pretty confident this combination of chat-stream and my project will amount to something I rely on daily.

**Pull request merged**
